engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
        mass_threshold: 50
    Similar code:
      enabled: true
      mass_threshold: 50
  eslint:
    enabled: true
    no-native-reassign:
      exceptions:
      - "onmessage"
  fixme:
    enabled: true
ratings:
  paths:
  - "src/*.js"
  - "feature-worker.js"
exclude_paths:
- "jsap.js"
- "js-xtract/*"
- "templates/*"
